# coding=utf-8
__author__ = 'siemienik'

LANGUAGES_SET = [
    ["English",
     "The Old Testament canon entered into Christian use in the Greek Septuagint translations and original books, and their differing lists of texts. In addition to the Septuagint, Christianity subsequently added various writings that would become the New Testament. Somewhat different lists of accepted works continued to develop in antiquity. In the 4th century a series of synods produced a list of texts equal to the 39, 4651,54, or 57 book canon of the Old Testament and to the 27-book canon of the New Testament that would be subsequently used to today, most notably the Synod of Hippo in AD 393. Also c. 400, Jerome produced a definitive Latin edition of the Bible see Vulgate, the canon of which, at the insistence of the Pope, was in accord with the earlier Synods. With the benefit of hindsight it can be said that this process effectively set the New Testament canon, although there are examples of other canonical lists in use after this time. A definitive list did not come from an Ecumenical Council until the Council of Trent 1545–63.During the Protestant Reformation, certain reformers proposed different canonical lists to those currently in use. Though not without debate, see Antilegomena, the list of New Testament books would come to remain the same; however, the Old Testament texts present in the Septuagint but not included in the Jewish canon fell out of favor. In time they would come to be removed from most Protestant canons. Hence, in a Catholic context, these texts are referred to as deuterocanonical books, whereas in a Protestant context they are referred to as the Apocrypha, which means \"hidden\", the label applied to all texts excluded from the biblical canon but which were in the Septuagint. It should also be noted that Catholics and Protestants both describe certain other books, such as the Acts of Peter, as apocryphal.citation needed Thus, the Protestant Old Testament of today has a 39-book canon—the number of books though not the content varies from the Jewish Tanakh only because of a different method of division—while the Roman Catholic Church recognizes 46 books "],
    ["Polski",
     """Do IV wieku n.e. nie było powszechnie przyjmowanego kanonu Biblii. Lokalne kościoły, jak i poszczególne regiony, miały swoje własne podejście do kanonu. Na Wschodzie odrzucano Apokalipsę, na Zachodzie – List do Hebrajczyków, a do pism kanonicznych zaliczano np. List Barnaby. Kościół Syryjski początkowo stosował kanon 22 ksiąg. W innych kościołach czytano Diatessaron, Pasterz Hermasa, Apokalipsę Piotra i inne księgi uznawane przez innych za apokryficzne. Jedne z pierwszych wzmianek o przyjętym w starożytnym Kościele zestawie ksiąg kanonicznych pojawiają się w zachowanych pismach autorów chrześcijańskich IV wieku – m.in. św. Atanazego, św. Augustyna, św. Hieronima, św. Rufina. W tym też okresie podejmowano próby sformalizowania tradycyjnego kanonu – m.in. na lokalnych synodach w Hipponie w 393 roku i w Kartaginie w 397 roku. Kościół Wschodni uznał postanowienia tych synodów za wiążące na synodzie trullańskim. W późniejszym czasie przyjął inny, obszerniejszy kanon, który zmieniano na przestrzeni wieków. Różnice pomiędzy kanonem przyjętym przez Kościoły Wschodnie a kanonem przyjętym przez Kościół Zachodni istnieją do dzisiaj.Protestancki kanon jest identyczny z kanonem zawartym w Prologus Galeatus św. Hieronima.Księgi starotestamentalne, które nie wchodzą w skład kanonu hebrajskiego, a zaliczają się do katolickiego, katolicy i prawosławni nazywają księgami deuterokanonicznymi. Przez żydów i protestantów są one określane jako apokryfy."""],
    ["Deutsch",
     """Als Bibel wird eine Sammlung von Schriften bezeichnet, die als Heilige Schriften Grundlage des Glaubens der Christen ist und von diesen auch Buch der Bücher genannt wird. Es handelt sich um eine Zusammenstellung von „Büchern“ (griechisch: βιβλία biblía) aus dem Kulturraum der Levante und dem Vorderen Orient, die im Verlauf von mehr als einem Jahrtausend entstanden sind und für das Christentum normativ sind (man sagt deshalb auch, sie gehören zum Kanon).Die Heilige Schrift der Juden, von ihnen meist als Tanach bezeichnet, oft auch nach dem ersten Teil als Tora, besteht aus den drei Teilen Tora (Lehre), Newiim (Propheten) und Ketuwim (Schriften). Diese Bücher bilden in anderer Anordnung als Altes Testament den ersten Hauptteil der christlichen Bibel, den das Neue Testament als zweiter Hauptteil ergänzt. Diese zweiteilige Bibel ist das am weitesten verbreitete und am häufigsten publizierte schriftliche Werk der Welt.Manchmal wird der kirchliche Begriff der Bibel auch auf den Tanach bezogen und dieser als „jüdische Bibel“ bezeichnet. Sie hat im Judentum für die Religionsausübung normativen Charakter. Im Orthodoxen Judentum gilt die Tora als von Gott an Moses und dem jüdischen Volk am Berg Sinai übergeben.Der Islam erkennt die Bibel als gültiges, jedoch von Menschen teilweise verfälschtes Offenbarungszeugnis Allahs an."""],
    ["Français",
     """Les Livres deutérocanoniques sont des textes écrits avant l'ère chrétienne qui ont été incorporés dans le canon de la Septante. Toutes les confessions chrétiennes dites « traditionnelles », c'est-à-dire existant avant la Réforme - comme les catholiques, les orthodoxes, les coptes, les chaldéens et les maronites - les ont toujours considérés comme faisant partie de la Bible. Cependant, ils n'ont pas été acceptés dans le canon par Luther, puisque lui-même se fonde sur le texte massorétique de la Bible hébraïque. Luther juge néanmoins ces livres utiles. Il suggère aussi de retirer l'épître de Jacques et la troisième lettre de Jean, qui pourtant font partie du Nouveau Testament.Ces livres de l'Ancien Testament rédigés en grecN 7 sont nommés « apocryphes » (du grec αποκρυφος, caché) par les protestants. Les catholiques les nomment « deutérocanoniques », c’est-à-dire « livres secondaires » dans le canon (du grec δευτερος, deuxième), ce qui est définitivement confirmé au concile de Trente en 1546.Certains des livres de la Septante n'ont pas été admis comme deutérocanoniques. Ils ne sont reconnus par aucune Église et sont appelés « apocryphes » ou « pseudépigraphes » (écrits sous une fausse signature). Ils forment avec d'autres de la même époque ce que l'on nomme aujourd'hui les « écrits intertestamentaires ». Il s'agit par exemple du livre du Pasteur d'Hermas, présent dans le Nouveau Testament, puis retiré du canon biblique au IIIe siècle. L'Épître de Barnabé fut elle aussi présente un temps dans le Nouveau Testament, avant d'être retirée par décision conciliaire."""],
]


LANGUAGES_TEST = [
    ["English no.1",
     "The Old Testament canon entered into Christian use in the Greek Septuagint translations and original books, and their differing lists of texts. In addition to the Septuagint, Christianity subsequently added various writings that would become the New Testament. Somewhat different lists of accepted works continued to develop in antiquity. In the 4th century a series of synods produced a list of texts equal to the 39, 4651,54, or 57 book canon of the Old Testament and to the 27-book canon of the New Testament that would be subsequently used to today, most notably the Synod of Hippo in AD 393. Also c. 400, Jerome produced a definitive Latin edition of the Bible see Vulgate, the canon of which, at the insistence of the Pope, was in accord with the earlier Synods. With the benefit of hindsight it can be said that this process effectively set the New Testament canon, although there are examples of other canonical lists in use after this time. A definitive list did not come from an Ecumenical Council until the Council of Trent 1545–63.During the Protestant Reformation, certain reformers proposed different canonical lists to those currently in use. Though not without debate, see Antilegomena, the list of New Testament books would come to remain the same; however, the Old Testament texts present in the Septuagint but not included in the Jewish canon fell out of favor. In time they would come to be removed from most Protestant canons. Hence, in a Catholic context, these texts are referred to as deuterocanonical books, whereas in a Protestant context they are referred to as the Apocrypha, which means \"hidden\", the label applied to all texts excluded from the biblical canon but which were in the Septuagint. It should also be noted that Catholics and Protestants both describe certain other books, such as the Acts of Peter, as apocryphal.citation needed Thus, the Protestant Old Testament of today has a 39-book canon—the number of books though not the content varies from the Jewish Tanakh only because of a different method of division—while the Roman Catholic Church recognizes 46 books "],
    ["Polski no.1",
     """Do IV wieku n.e. nie było powszechnie przyjmowanego kanonu Biblii. Lokalne kościoły, jak i poszczególne regiony, miały swoje własne podejście do kanonu. Na Wschodzie odrzucano Apokalipsę, na Zachodzie – List do Hebrajczyków, a do pism kanonicznych zaliczano np. List Barnaby. Kościół Syryjski początkowo stosował kanon 22 ksiąg. W innych kościołach czytano Diatessaron, Pasterz Hermasa, Apokalipsę Piotra i inne księgi uznawane przez innych za apokryficzne. Jedne z pierwszych wzmianek o przyjętym w starożytnym Kościele zestawie ksiąg kanonicznych pojawiają się w zachowanych pismach autorów chrześcijańskich IV wieku – m.in. św. Atanazego, św. Augustyna, św. Hieronima, św. Rufina. W tym też okresie podejmowano próby sformalizowania tradycyjnego kanonu – m.in. na lokalnych synodach w Hipponie w 393 roku i w Kartaginie w 397 roku. Kościół Wschodni uznał postanowienia tych synodów za wiążące na synodzie trullańskim. W późniejszym czasie przyjął inny, obszerniejszy kanon, który zmieniano na przestrzeni wieków. Różnice pomiędzy kanonem przyjętym przez Kościoły Wschodnie a kanonem przyjętym przez Kościół Zachodni istnieją do dzisiaj.Protestancki kanon jest identyczny z kanonem zawartym w Prologus Galeatus św. Hieronima.Księgi starotestamentalne, które nie wchodzą w skład kanonu hebrajskiego, a zaliczają się do katolickiego, katolicy i prawosławni nazywają księgami deuterokanonicznymi. Przez żydów i protestantów są one określane jako apokryfy."""],
    ["Deutsch no.1",
     """Als Bibel wird eine Sammlung von Schriften bezeichnet, die als Heilige Schriften Grundlage des Glaubens der Christen ist und von diesen auch Buch der Bücher genannt wird. Es handelt sich um eine Zusammenstellung von „Büchern“ (griechisch: βιβλία biblía) aus dem Kulturraum der Levante und dem Vorderen Orient, die im Verlauf von mehr als einem Jahrtausend entstanden sind und für das Christentum normativ sind (man sagt deshalb auch, sie gehören zum Kanon).Die Heilige Schrift der Juden, von ihnen meist als Tanach bezeichnet, oft auch nach dem ersten Teil als Tora, besteht aus den drei Teilen Tora (Lehre), Newiim (Propheten) und Ketuwim (Schriften). Diese Bücher bilden in anderer Anordnung als Altes Testament den ersten Hauptteil der christlichen Bibel, den das Neue Testament als zweiter Hauptteil ergänzt. Diese zweiteilige Bibel ist das am weitesten verbreitete und am häufigsten publizierte schriftliche Werk der Welt.Manchmal wird der kirchliche Begriff der Bibel auch auf den Tanach bezogen und dieser als „jüdische Bibel“ bezeichnet. Sie hat im Judentum für die Religionsausübung normativen Charakter. Im Orthodoxen Judentum gilt die Tora als von Gott an Moses und dem jüdischen Volk am Berg Sinai übergeben.Der Islam erkennt die Bibel als gültiges, jedoch von Menschen teilweise verfälschtes Offenbarungszeugnis Allahs an."""],
    ["Français no.1",
     """Les Livres deutérocanoniques sont des textes écrits avant l'ère chrétienne qui ont été incorporés dans le canon de la Septante. Toutes les confessions chrétiennes dites « traditionnelles », c'est-à-dire existant avant la Réforme - comme les catholiques, les orthodoxes, les coptes, les chaldéens et les maronites - les ont toujours considérés comme faisant partie de la Bible. Cependant, ils n'ont pas été acceptés dans le canon par Luther, puisque lui-même se fonde sur le texte massorétique de la Bible hébraïque. Luther juge néanmoins ces livres utiles. Il suggère aussi de retirer l'épître de Jacques et la troisième lettre de Jean, qui pourtant font partie du Nouveau Testament.Ces livres de l'Ancien Testament rédigés en grecN 7 sont nommés « apocryphes » (du grec αποκρυφος, caché) par les protestants. Les catholiques les nomment « deutérocanoniques », c’est-à-dire « livres secondaires » dans le canon (du grec δευτερος, deuxième), ce qui est définitivement confirmé au concile de Trente en 1546.Certains des livres de la Septante n'ont pas été admis comme deutérocanoniques. Ils ne sont reconnus par aucune Église et sont appelés « apocryphes » ou « pseudépigraphes » (écrits sous une fausse signature). Ils forment avec d'autres de la même époque ce que l'on nomme aujourd'hui les « écrits intertestamentaires ». Il s'agit par exemple du livre du Pasteur d'Hermas, présent dans le Nouveau Testament, puis retiré du canon biblique au IIIe siècle. L'Épître de Barnabé fut elle aussi présente un temps dans le Nouveau Testament, avant d'être retirée par décision conciliaire."""],
    ["Polski no.2",
     """lubie placki dlatego bardzo dużo ich zjem, bo właśnie wszystkie z domu zjadłem, były wyborne!"""],

]